package com.example.turistguide.Model;

public enum AttractionTags {
    FORLYSTELSESPARK,MUSEUM,HISTORISK,KIRKE,SLOT,PARK,ZOO,NATUR,ARKITEKTUR,
    TEATER,BIOGRAF,SHOPPING,RESTAURANT,CAFÉ,
    FAMILIEVENLIG,BØRNEVENLIG,VOKSEN,UNGE,
    GRATIS, $,$$,$$$,STUDIERABAT,PENSIONISTRABAT,BØRNERABAT


}
